/* Generated by Yosys 0.9+4081 (git sha1 4446cfa5, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

(* dynports =  1  *)
(* hdlname = "\\apb_master" *)
(* src = "apb_master.v:1.1-98.10" *)
module \$paramod\apb_master\c_apb_num_slaves=s32'00000000000000000000000000000001 (PCLK, PRESETn, STREQ, SWRT, SSEL, SADDR, SWDATA, SRDATA, PADDR, PPROT, PSELx, PENABLE, PWRITE, PWDATA, PSTRB, PREADY, PRDATA, PSLVERR, m_apb_prdata2, m_apb_prdata3, m_apb_prdata4, m_apb_prdata5, m_apb_prdata6, m_apb_prdata7, m_apb_prdata8, m_apb_prdata9, m_apb_prdata10, m_apb_prdata11, m_apb_prdata12, m_apb_prdata13, m_apb_prdata14, m_apb_prdata15, m_apb_prdata16, Out_State);
  (* src = "apb_master.v:59.1-85.4" *)
  wire [1:0] _0_;
  wire _1_;
  wire _2_;
  (* src = "apb_master.v:51.20-51.29" *)
  output [1:0] Out_State;
  (* src = "apb_master.v:24.20-24.25" *)
  output [31:0] PADDR;
  (* src = "apb_master.v:14.19-14.23" *)
  input PCLK;
  (* src = "apb_master.v:27.19-27.26" *)
  output PENABLE;
  (* src = "apb_master.v:25.20-25.25" *)
  output [2:0] PPROT;
  (* src = "apb_master.v:33.20-33.26" *)
  input [31:0] PRDATA;
  (* src = "apb_master.v:32.33-32.39" *)
  input PREADY;
  (* src = "apb_master.v:15.19-15.26" *)
  input PRESETn;
  (* src = "apb_master.v:26.34-26.39" *)
  output PSELx;
  (* src = "apb_master.v:49.36-49.43" *)
  input PSLVERR;
  (* src = "apb_master.v:30.20-30.25" *)
  output [3:0] PSTRB;
  (* src = "apb_master.v:29.20-29.26" *)
  output [31:0] PWDATA;
  (* src = "apb_master.v:28.20-28.26" *)
  output PWRITE;
  (* src = "apb_master.v:20.20-20.25" *)
  input [31:0] SADDR;
  (* src = "apb_master.v:22.20-22.26" *)
  output [31:0] SRDATA;
  (* src = "apb_master.v:19.33-19.37" *)
  input SSEL;
  (* src = "apb_master.v:17.18-17.23" *)
  input STREQ;
  (* src = "apb_master.v:21.20-21.26" *)
  input [31:0] SWDATA;
  (* src = "apb_master.v:18.18-18.22" *)
  input SWRT;
  (* src = "apb_master.v:42.19-42.33" *)
  input [31:0] m_apb_prdata10;
  (* src = "apb_master.v:43.19-43.33" *)
  input [31:0] m_apb_prdata11;
  (* src = "apb_master.v:44.19-44.33" *)
  input [31:0] m_apb_prdata12;
  (* src = "apb_master.v:45.19-45.33" *)
  input [31:0] m_apb_prdata13;
  (* src = "apb_master.v:46.19-46.33" *)
  input [31:0] m_apb_prdata14;
  (* src = "apb_master.v:47.19-47.33" *)
  input [31:0] m_apb_prdata15;
  (* src = "apb_master.v:48.19-48.33" *)
  input [31:0] m_apb_prdata16;
  (* src = "apb_master.v:34.19-34.32" *)
  input [31:0] m_apb_prdata2;
  (* src = "apb_master.v:35.19-35.32" *)
  input [31:0] m_apb_prdata3;
  (* src = "apb_master.v:36.19-36.32" *)
  input [31:0] m_apb_prdata4;
  (* src = "apb_master.v:37.19-37.32" *)
  input [31:0] m_apb_prdata5;
  (* src = "apb_master.v:38.19-38.32" *)
  input [31:0] m_apb_prdata6;
  (* src = "apb_master.v:39.19-39.32" *)
  input [31:0] m_apb_prdata7;
  (* src = "apb_master.v:40.19-40.32" *)
  input [31:0] m_apb_prdata8;
  (* src = "apb_master.v:41.19-41.32" *)
  input [31:0] m_apb_prdata9;
  (* src = "apb_master.v:57.11-57.16" *)
  wire [1:0] state;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _3_ (
    .A(state[1]),
    .SLEEP(PREADY),
    .X(_2_)
  );
  sky130_fd_sc_hd__nor3b_1 _4_ (
    .A(state[0]),
    .B(_2_),
    .C_N(STREQ),
    .Y(_0_[0])
  );
  sky130_fd_sc_hd__nand2_1 _5_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_1_)
  );
  sky130_fd_sc_hd__o21a_1 _6_ (
    .A1(state[0]),
    .A2(_2_),
    .B1(_1_),
    .X(_0_[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _7_ (
    .A(state[1]),
    .SLEEP(state[0]),
    .X(PENABLE)
  );
  (* src = "apb_master.v:59.1-85.4" *)
  sky130_fd_sc_hd__dfxtp_1 _8_ (
    .CLK(PCLK),
    .D(_0_[0]),
    .Q(state[0])
  );
  (* src = "apb_master.v:59.1-85.4" *)
  sky130_fd_sc_hd__dfxtp_1 _9_ (
    .CLK(PCLK),
    .D(_0_[1]),
    .Q(state[1])
  );
  assign Out_State = state;
  assign PADDR = SADDR;
  assign PSELx = SSEL;
  assign PSTRB = 4'hf;
  assign PWDATA = SWDATA;
  assign PWRITE = SWRT;
  assign SRDATA = PRDATA;
endmodule

(* dynports =  1  *)
(* hdlname = "\\flop" *)
(* src = "flop.v:2.1-16.10" *)
module \$paramod\flop\width=s32'00000000000000000000000000000001 (clk, rst, d, q);
  (* src = "flop.v:3.31-3.34" *)
  input clk;
  (* src = "flop.v:5.31-5.32" *)
  input d;
  (* src = "flop.v:6.31-6.32" *)
  output q;
  (* src = "flop.v:4.31-4.34" *)
  input rst;
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _0_ (
    .CLK(clk),
    .D(d),
    .Q(q),
    .RESET_B(rst)
  );
endmodule

(* dynports =  1  *)
(* hdlname = "\\flop" *)
(* src = "flop.v:2.1-16.10" *)
module \$paramod\flop\width=s32'00000000000000000000000000000010 (clk, rst, d, q);
  (* src = "flop.v:3.31-3.34" *)
  input clk;
  (* src = "flop.v:5.31-5.32" *)
  input [1:0] d;
  (* src = "flop.v:6.31-6.32" *)
  output [1:0] q;
  (* src = "flop.v:4.31-4.34" *)
  input rst;
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _0_ (
    .CLK(clk),
    .D(d[0]),
    .Q(q[0]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1_ (
    .CLK(clk),
    .D(d[1]),
    .Q(q[1]),
    .RESET_B(rst)
  );
endmodule

(* dynports =  1  *)
(* hdlname = "\\flop" *)
(* src = "flop.v:2.1-16.10" *)
module \$paramod\flop\width=s32'00000000000000000000000000100000 (clk, rst, d, q);
  (* src = "flop.v:3.31-3.34" *)
  input clk;
  (* src = "flop.v:5.31-5.32" *)
  input [31:0] d;
  (* src = "flop.v:6.31-6.32" *)
  output [31:0] q;
  (* src = "flop.v:4.31-4.34" *)
  input rst;
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _00_ (
    .CLK(clk),
    .D(d[0]),
    .Q(q[0]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _01_ (
    .CLK(clk),
    .D(d[1]),
    .Q(q[1]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _02_ (
    .CLK(clk),
    .D(d[2]),
    .Q(q[2]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _03_ (
    .CLK(clk),
    .D(d[3]),
    .Q(q[3]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _04_ (
    .CLK(clk),
    .D(d[4]),
    .Q(q[4]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _05_ (
    .CLK(clk),
    .D(d[5]),
    .Q(q[5]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _06_ (
    .CLK(clk),
    .D(d[6]),
    .Q(q[6]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _07_ (
    .CLK(clk),
    .D(d[7]),
    .Q(q[7]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _08_ (
    .CLK(clk),
    .D(d[8]),
    .Q(q[8]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _09_ (
    .CLK(clk),
    .D(d[9]),
    .Q(q[9]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _10_ (
    .CLK(clk),
    .D(d[10]),
    .Q(q[10]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _11_ (
    .CLK(clk),
    .D(d[11]),
    .Q(q[11]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _12_ (
    .CLK(clk),
    .D(d[12]),
    .Q(q[12]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _13_ (
    .CLK(clk),
    .D(d[13]),
    .Q(q[13]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(clk),
    .D(d[14]),
    .Q(q[14]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _15_ (
    .CLK(clk),
    .D(d[15]),
    .Q(q[15]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _16_ (
    .CLK(clk),
    .D(d[16]),
    .Q(q[16]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _17_ (
    .CLK(clk),
    .D(d[17]),
    .Q(q[17]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _18_ (
    .CLK(clk),
    .D(d[18]),
    .Q(q[18]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _19_ (
    .CLK(clk),
    .D(d[19]),
    .Q(q[19]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _20_ (
    .CLK(clk),
    .D(d[20]),
    .Q(q[20]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _21_ (
    .CLK(clk),
    .D(d[21]),
    .Q(q[21]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _22_ (
    .CLK(clk),
    .D(d[22]),
    .Q(q[22]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _23_ (
    .CLK(clk),
    .D(d[23]),
    .Q(q[23]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _24_ (
    .CLK(clk),
    .D(d[24]),
    .Q(q[24]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _25_ (
    .CLK(clk),
    .D(d[25]),
    .Q(q[25]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _26_ (
    .CLK(clk),
    .D(d[26]),
    .Q(q[26]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _27_ (
    .CLK(clk),
    .D(d[27]),
    .Q(q[27]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _28_ (
    .CLK(clk),
    .D(d[28]),
    .Q(q[28]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _29_ (
    .CLK(clk),
    .D(d[29]),
    .Q(q[29]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _30_ (
    .CLK(clk),
    .D(d[30]),
    .Q(q[30]),
    .RESET_B(rst)
  );
  (* src = "flop.v:9.1-14.4" *)
  sky130_fd_sc_hd__dfrtp_1 _31_ (
    .CLK(clk),
    .D(d[31]),
    .Q(q[31]),
    .RESET_B(rst)
  );
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "axi_apb_bridge.v:5.1-373.10" *)
module axi_apb_bridge(s_axi_clk, s_axi_aresetn, s_axi_awaddr, s_axi_awvalid, s_axi_awready, s_axi_wdata, s_axi_wvalid, s_axi_wstrb, s_axi_wready, s_axi_bresp, s_axi_bvalid, s_axi_bready, s_axi_araddr, s_axi_arvalid, s_axi_arready, s_axi_rresp, s_axi_rvalid, s_axi_rdata, s_axi_rready, s_axi_arprot, s_axi_awprot, m_apb_paddr, m_apb_pprot, m_apb_psel, m_apb_penable, m_apb_pwrite, m_apb_pwdata, m_apb_pstrb, m_apb_pready, m_apb_prdata, m_apb_prdata2, m_apb_prdata3, m_apb_prdata4, m_apb_prdata5, m_apb_prdata6, m_apb_prdata7, m_apb_prdata8, m_apb_prdata9, m_apb_prdata10, m_apb_prdata11, m_apb_prdata12, m_apb_prdata13, m_apb_prdata14, m_apb_prdata15, m_apb_prdata16, m_apb_pslverr);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  (* src = "axi_apb_bridge.v:137.29-137.34" *)
  wire [31:0] SADDR;
  (* src = "axi_apb_bridge.v:135.29-135.35" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] SRDATA;
  (* src = "axi_apb_bridge.v:131.29-131.33" *)
  wire SSEL;
  (* src = "axi_apb_bridge.v:139.29-139.34" *)
  wire STREQ;
  (* src = "axi_apb_bridge.v:134.29-134.35" *)
  wire [31:0] SWDATA;
  (* src = "axi_apb_bridge.v:133.29-133.33" *)
  wire SWRT;
  (* src = "axi_apb_bridge.v:138.29-138.38" *)
  wire apb_reset;
  (* src = "axi_apb_bridge.v:128.11-128.27" *)
  wire apb_transfer_req;
  (* src = "axi_apb_bridge.v:82.44-82.62" *)
  wire axi_write_data_nxt;
  (* src = "axi_apb_bridge.v:78.12-78.30" *)
  wire [31:0] axi_write_data_reg;
  (* src = "axi_apb_bridge.v:127.11-127.23" *)
  wire [2:0] bridge_state;
  (* src = "axi_apb_bridge.v:105.12-105.25" *)
  wire [31:0] captured_addr;
  (* src = "axi_apb_bridge.v:106.12-106.29" *)
  wire [31:0] captured_addr_nxt;
  (* src = "axi_apb_bridge.v:344.12-344.17" *)
  wire [31:0] dummy;
  (* src = "axi_apb_bridge.v:39.33-39.44" *)
  output [31:0] m_apb_paddr;
  (* src = "axi_apb_bridge.v:42.33-42.46" *)
  output m_apb_penable;
  (* src = "axi_apb_bridge.v:40.33-40.44" *)
  output [2:0] m_apb_pprot;
  (* src = "axi_apb_bridge.v:47.33-47.45" *)
  input [31:0] m_apb_prdata;
  (* src = "axi_apb_bridge.v:56.33-56.47" *)
  input [31:0] m_apb_prdata10;
  (* src = "axi_apb_bridge.v:57.33-57.47" *)
  input [31:0] m_apb_prdata11;
  (* src = "axi_apb_bridge.v:58.33-58.47" *)
  input [31:0] m_apb_prdata12;
  (* src = "axi_apb_bridge.v:59.33-59.47" *)
  input [31:0] m_apb_prdata13;
  (* src = "axi_apb_bridge.v:60.33-60.47" *)
  input [31:0] m_apb_prdata14;
  (* src = "axi_apb_bridge.v:61.33-61.47" *)
  input [31:0] m_apb_prdata15;
  (* src = "axi_apb_bridge.v:62.33-62.47" *)
  input [31:0] m_apb_prdata16;
  (* src = "axi_apb_bridge.v:48.33-48.46" *)
  input [31:0] m_apb_prdata2;
  (* src = "axi_apb_bridge.v:49.33-49.46" *)
  input [31:0] m_apb_prdata3;
  (* src = "axi_apb_bridge.v:50.33-50.46" *)
  input [31:0] m_apb_prdata4;
  (* src = "axi_apb_bridge.v:51.33-51.46" *)
  input [31:0] m_apb_prdata5;
  (* src = "axi_apb_bridge.v:52.33-52.46" *)
  input [31:0] m_apb_prdata6;
  (* src = "axi_apb_bridge.v:53.33-53.46" *)
  input [31:0] m_apb_prdata7;
  (* src = "axi_apb_bridge.v:54.33-54.46" *)
  input [31:0] m_apb_prdata8;
  (* src = "axi_apb_bridge.v:55.33-55.46" *)
  input [31:0] m_apb_prdata9;
  (* src = "axi_apb_bridge.v:46.33-46.45" *)
  input m_apb_pready;
  (* src = "axi_apb_bridge.v:41.33-41.43" *)
  output m_apb_psel;
  (* src = "axi_apb_bridge.v:63.33-63.46" *)
  input m_apb_pslverr;
  (* src = "axi_apb_bridge.v:45.33-45.44" *)
  output [3:0] m_apb_pstrb;
  (* src = "axi_apb_bridge.v:44.33-44.45" *)
  output [31:0] m_apb_pwdata;
  (* src = "axi_apb_bridge.v:43.33-43.45" *)
  output m_apb_pwrite;
  (* src = "axi_apb_bridge.v:100.12-100.25" *)
  wire [31:0] read_data_nxt;
  (* src = "axi_apb_bridge.v:99.12-99.25" *)
  wire [31:0] read_data_reg;
  (* src = "axi_apb_bridge.v:110.11-110.20" *)
  wire [1:0] read_resp;
  (* src = "axi_apb_bridge.v:111.11-111.24" *)
  wire [1:0] read_resp_nxt;
  (* src = "axi_apb_bridge.v:90.9-90.23" *)
  wire read_valid_nxt;
  (* src = "axi_apb_bridge.v:89.12-89.26" *)
  wire read_valid_reg;
  (* src = "axi_apb_bridge.v:28.33-28.45" *)
  input [31:0] s_axi_araddr;
  (* src = "axi_apb_bridge.v:17.33-17.46" *)
  input s_axi_aresetn;
  (* src = "axi_apb_bridge.v:36.33-36.45" *)
  input [2:0] s_axi_arprot;
  (* src = "axi_apb_bridge.v:30.33-30.46" *)
  output s_axi_arready;
  (* src = "axi_apb_bridge.v:29.33-29.46" *)
  input s_axi_arvalid;
  (* src = "axi_apb_bridge.v:18.33-18.45" *)
  input [31:0] s_axi_awaddr;
  (* src = "axi_apb_bridge.v:37.33-37.45" *)
  input [2:0] s_axi_awprot;
  (* src = "axi_apb_bridge.v:20.33-20.46" *)
  output s_axi_awready;
  (* src = "axi_apb_bridge.v:19.33-19.46" *)
  input s_axi_awvalid;
  (* src = "axi_apb_bridge.v:27.33-27.45" *)
  input s_axi_bready;
  (* src = "axi_apb_bridge.v:25.33-25.44" *)
  output [1:0] s_axi_bresp;
  (* src = "axi_apb_bridge.v:26.33-26.45" *)
  output s_axi_bvalid;
  (* src = "axi_apb_bridge.v:16.33-16.42" *)
  input s_axi_clk;
  (* src = "axi_apb_bridge.v:33.33-33.44" *)
  output [31:0] s_axi_rdata;
  (* src = "axi_apb_bridge.v:34.33-34.45" *)
  input s_axi_rready;
  (* src = "axi_apb_bridge.v:31.33-31.44" *)
  output [1:0] s_axi_rresp;
  (* src = "axi_apb_bridge.v:32.33-32.45" *)
  output s_axi_rvalid;
  (* src = "axi_apb_bridge.v:21.33-21.44" *)
  input [31:0] s_axi_wdata;
  (* src = "axi_apb_bridge.v:24.33-24.45" *)
  output s_axi_wready;
  (* src = "axi_apb_bridge.v:23.33-23.44" *)
  input [3:0] s_axi_wstrb;
  (* src = "axi_apb_bridge.v:22.33-22.45" *)
  input s_axi_wvalid;
  (* src = "axi_apb_bridge.v:132.29-132.34" *)
  wire [1:0] state;
  (* src = "axi_apb_bridge.v:130.12-130.16" *)
  (* unused_bits = "0 1" *)
  wire [1:0] strb;
  (* src = "axi_apb_bridge.v:120.12-120.27" *)
  wire [31:0] timeout_counter;
  (* src = "axi_apb_bridge.v:121.12-121.31" *)
  wire [31:0] timeout_counter_nxt;
  (* src = "axi_apb_bridge.v:84.12-84.26" *)
  wire write_happened;
  (* src = "axi_apb_bridge.v:85.12-85.30" *)
  wire write_happened_nxt;
  (* src = "axi_apb_bridge.v:222.8-222.17" *)
  wire write_req;
  (* src = "axi_apb_bridge.v:115.11-115.21" *)
  wire [1:0] write_resp;
  (* src = "axi_apb_bridge.v:116.11-116.25" *)
  wire [1:0] write_resp_nxt;
  (* src = "axi_apb_bridge.v:95.9-95.29" *)
  wire write_resp_valid_nxt;
  (* src = "axi_apb_bridge.v:94.12-94.32" *)
  wire write_resp_valid_reg;
  sky130_fd_sc_hd__clkinv_1 _323_ (
    .A(bridge_state[1]),
    .Y(_214_)
  );
  sky130_fd_sc_hd__clkinv_1 _324_ (
    .A(s_axi_wvalid),
    .Y(_215_)
  );
  sky130_fd_sc_hd__a21oi_1 _325_ (
    .A1(_215_),
    .A2(s_axi_awvalid),
    .B1(s_axi_arvalid),
    .Y(_216_)
  );
  sky130_fd_sc_hd__or3b_1 _326_ (
    .A(bridge_state[1]),
    .B(bridge_state[2]),
    .C_N(bridge_state[0]),
    .X(_217_)
  );
  sky130_fd_sc_hd__nand2b_1 _327_ (
    .A_N(state[0]),
    .B(state[1]),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nand2_1 _328_ (
    .A(m_apb_psel),
    .B(m_apb_pready),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nor2_1 _329_ (
    .A(_218_),
    .B(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nand4b_1 _330_ (
    .A_N(state[0]),
    .B(state[1]),
    .C(m_apb_psel),
    .D(m_apb_pready),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(_217_),
    .B(_221_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nand3_1 _332_ (
    .A(bridge_state[0]),
    .B(_214_),
    .C(bridge_state[2]),
    .Y(_223_)
  );
  sky130_fd_sc_hd__clkinv_1 _333_ (
    .A(_223_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nor2_1 _334_ (
    .A(bridge_state[0]),
    .B(bridge_state[1]),
    .Y(_225_)
  );
  sky130_fd_sc_hd__nor3_1 _335_ (
    .A(bridge_state[0]),
    .B(bridge_state[1]),
    .C(bridge_state[2]),
    .Y(_226_)
  );
  sky130_fd_sc_hd__nand2b_1 _336_ (
    .A_N(s_axi_bready),
    .B(write_happened),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nand3b_1 _337_ (
    .A_N(state[0]),
    .B(_226_),
    .C(_227_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nor2_1 _338_ (
    .A(bridge_state[2]),
    .B(_215_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nand2_1 _339_ (
    .A(bridge_state[0]),
    .B(bridge_state[1]),
    .Y(_230_)
  );
  sky130_fd_sc_hd__o22ai_1 _340_ (
    .A1(_216_),
    .A2(_228_),
    .B1(_229_),
    .B2(_230_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nand2b_1 _341_ (
    .A_N(state[1]),
    .B(state[0]),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nand2_1 _342_ (
    .A(bridge_state[0]),
    .B(state[1]),
    .Y(_233_)
  );
  sky130_fd_sc_hd__a21oi_1 _343_ (
    .A1(_232_),
    .A2(_233_),
    .B1(_217_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nand3_1 _344_ (
    .A(s_axi_rready),
    .B(_216_),
    .C(_222_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__a21oi_1 _345_ (
    .A1(s_axi_rready),
    .A2(_216_),
    .B1(_223_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__a211o_1 _346_ (
    .A1(_234_),
    .A2(_235_),
    .B1(_236_),
    .C1(_231_),
    .X(_001_)
  );
  sky130_fd_sc_hd__nand2b_1 _347_ (
    .A_N(_218_),
    .B(_219_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nor4_1 _348_ (
    .A(timeout_counter[15]),
    .B(timeout_counter[14]),
    .C(timeout_counter[13]),
    .D(timeout_counter[12]),
    .Y(_238_)
  );
  sky130_fd_sc_hd__clkinv_1 _349_ (
    .A(_238_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nor4_1 _350_ (
    .A(timeout_counter[3]),
    .B(timeout_counter[2]),
    .C(timeout_counter[1]),
    .D(timeout_counter[0]),
    .Y(_240_)
  );
  sky130_fd_sc_hd__or4_1 _351_ (
    .A(timeout_counter[3]),
    .B(timeout_counter[2]),
    .C(timeout_counter[1]),
    .D(timeout_counter[0]),
    .X(_241_)
  );
  sky130_fd_sc_hd__nor2_1 _352_ (
    .A(timeout_counter[29]),
    .B(timeout_counter[28]),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nor4_1 _353_ (
    .A(timeout_counter[27]),
    .B(timeout_counter[26]),
    .C(timeout_counter[25]),
    .D(timeout_counter[24]),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand4_1 _354_ (
    .A(_238_),
    .B(_240_),
    .C(_242_),
    .D(_243_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nor4_1 _355_ (
    .A(timeout_counter[7]),
    .B(timeout_counter[6]),
    .C(timeout_counter[5]),
    .D(timeout_counter[4]),
    .Y(_245_)
  );
  sky130_fd_sc_hd__or4_1 _356_ (
    .A(timeout_counter[7]),
    .B(timeout_counter[6]),
    .C(timeout_counter[5]),
    .D(timeout_counter[4]),
    .X(_246_)
  );
  sky130_fd_sc_hd__nor4_1 _357_ (
    .A(timeout_counter[11]),
    .B(timeout_counter[10]),
    .C(timeout_counter[9]),
    .D(timeout_counter[8]),
    .Y(_247_)
  );
  sky130_fd_sc_hd__clkinv_1 _358_ (
    .A(_247_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nand2_1 _359_ (
    .A(_245_),
    .B(_247_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__nor4_1 _360_ (
    .A(timeout_counter[23]),
    .B(timeout_counter[22]),
    .C(timeout_counter[21]),
    .D(timeout_counter[20]),
    .Y(_250_)
  );
  sky130_fd_sc_hd__nor4_1 _361_ (
    .A(timeout_counter[19]),
    .B(timeout_counter[18]),
    .C(timeout_counter[17]),
    .D(timeout_counter[16]),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nand2_1 _362_ (
    .A(_250_),
    .B(_251_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nand4_1 _363_ (
    .A(_245_),
    .B(_247_),
    .C(_250_),
    .D(_251_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__nor2_1 _364_ (
    .A(timeout_counter[26]),
    .B(timeout_counter[25]),
    .Y(_254_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _365_ (
    .A(_244_),
    .SLEEP(_253_),
    .X(_255_)
  );
  sky130_fd_sc_hd__nor2_1 _366_ (
    .A(timeout_counter[30]),
    .B(_255_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nor3_1 _367_ (
    .A(timeout_counter[30]),
    .B(timeout_counter[31]),
    .C(_255_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__nor4_1 _368_ (
    .A(timeout_counter[30]),
    .B(timeout_counter[31]),
    .C(_237_),
    .D(_255_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__nand2_1 _369_ (
    .A(_232_),
    .B(_237_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__a21oi_1 _370_ (
    .A1(bridge_state[1]),
    .A2(state[1]),
    .B1(_259_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__or3b_1 _371_ (
    .A(bridge_state[0]),
    .B(bridge_state[2]),
    .C_N(bridge_state[1]),
    .X(_261_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _372_ (
    .A(s_axi_awvalid),
    .SLEEP(s_axi_arvalid),
    .X(_262_)
  );
  sky130_fd_sc_hd__and2_0 _373_ (
    .A(s_axi_rready),
    .B(_222_),
    .X(_263_)
  );
  sky130_fd_sc_hd__nand2_1 _374_ (
    .A(s_axi_rready),
    .B(_222_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _375_ (
    .A(s_axi_rready),
    .SLEEP(_223_),
    .X(_265_)
  );
  sky130_fd_sc_hd__nand2_1 _376_ (
    .A(_228_),
    .B(_264_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__o21ai_0 _377_ (
    .A1(_265_),
    .A2(_266_),
    .B1(_262_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__nand2_1 _378_ (
    .A(bridge_state[2]),
    .B(_225_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nand3_1 _379_ (
    .A(bridge_state[2]),
    .B(s_axi_awvalid),
    .C(_225_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nand2_1 _380_ (
    .A(bridge_state[1]),
    .B(bridge_state[2]),
    .Y(_270_)
  );
  sky130_fd_sc_hd__o21ai_0 _381_ (
    .A1(bridge_state[0]),
    .A2(bridge_state[2]),
    .B1(bridge_state[1]),
    .Y(_271_)
  );
  sky130_fd_sc_hd__nand2_1 _382_ (
    .A(s_axi_awvalid),
    .B(_265_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__and3_1 _383_ (
    .A(_267_),
    .B(_269_),
    .C(_271_),
    .X(_273_)
  );
  sky130_fd_sc_hd__o41ai_1 _384_ (
    .A1(_220_),
    .A2(_258_),
    .A3(_260_),
    .A4(_261_),
    .B1(_273_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _385_ (
    .A(_217_),
    .B(_237_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__nor2_1 _386_ (
    .A(_237_),
    .B(_261_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__a221oi_1 _387_ (
    .A1(m_apb_psel),
    .A2(m_apb_pready),
    .B1(_217_),
    .B2(_261_),
    .C1(_218_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__o41ai_1 _388_ (
    .A1(timeout_counter[30]),
    .A2(timeout_counter[31]),
    .A3(_244_),
    .A4(_253_),
    .B1(_276_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__or3_1 _389_ (
    .A(timeout_counter[30]),
    .B(_255_),
    .C(_277_),
    .X(_278_)
  );
  sky130_fd_sc_hd__nor2_1 _390_ (
    .A(_221_),
    .B(_261_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__nor3_1 _391_ (
    .A(_222_),
    .B(_226_),
    .C(_279_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__o211ai_1 _392_ (
    .A1(_255_),
    .A2(_277_),
    .B1(_280_),
    .C1(timeout_counter[30]),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nand2_1 _393_ (
    .A(_278_),
    .B(_281_),
    .Y(timeout_counter_nxt[30])
  );
  sky130_fd_sc_hd__nand2_1 _394_ (
    .A(timeout_counter[29]),
    .B(_280_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _395_ (
    .A(timeout_counter[0]),
    .SLEEP(_277_),
    .X(_283_)
  );
  sky130_fd_sc_hd__or3_1 _396_ (
    .A(timeout_counter[2]),
    .B(timeout_counter[1]),
    .C(_283_),
    .X(_284_)
  );
  sky130_fd_sc_hd__nor2_1 _397_ (
    .A(_241_),
    .B(_277_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _398_ (
    .A(_241_),
    .SLEEP(_277_),
    .X(_286_)
  );
  sky130_fd_sc_hd__or4_1 _399_ (
    .A(_239_),
    .B(_241_),
    .C(_249_),
    .D(_277_),
    .X(_287_)
  );
  sky130_fd_sc_hd__or4_1 _400_ (
    .A(timeout_counter[25]),
    .B(timeout_counter[24]),
    .C(_252_),
    .D(_287_),
    .X(_288_)
  );
  sky130_fd_sc_hd__nor4_1 _401_ (
    .A(timeout_counter[28]),
    .B(timeout_counter[27]),
    .C(timeout_counter[26]),
    .D(_288_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__nor4_1 _402_ (
    .A(_241_),
    .B(_246_),
    .C(_248_),
    .D(_277_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__nand2_1 _403_ (
    .A(_238_),
    .B(_290_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__nand3_1 _404_ (
    .A(_238_),
    .B(_251_),
    .C(_290_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__nand4_1 _405_ (
    .A(_238_),
    .B(_250_),
    .C(_251_),
    .D(_290_),
    .Y(_293_)
  );
  sky130_fd_sc_hd__nor4b_1 _406_ (
    .A(timeout_counter[27]),
    .B(_293_),
    .C(timeout_counter[24]),
    .D_N(_254_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__or4_1 _407_ (
    .A(timeout_counter[6]),
    .B(timeout_counter[5]),
    .C(timeout_counter[4]),
    .D(_286_),
    .X(_295_)
  );
  sky130_fd_sc_hd__or4_1 _408_ (
    .A(timeout_counter[9]),
    .B(timeout_counter[8]),
    .C(timeout_counter[7]),
    .D(_295_),
    .X(_296_)
  );
  sky130_fd_sc_hd__mux2i_1 _409_ (
    .A0(_282_),
    .A1(timeout_counter[29]),
    .S(_289_),
    .Y(timeout_counter_nxt[29])
  );
  sky130_fd_sc_hd__nand2_1 _410_ (
    .A(timeout_counter[28]),
    .B(_280_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__o21bai_1 _411_ (
    .A1(_294_),
    .A2(_297_),
    .B1_N(_289_),
    .Y(timeout_counter_nxt[28])
  );
  sky130_fd_sc_hd__o211ai_1 _412_ (
    .A1(timeout_counter[26]),
    .A2(_288_),
    .B1(_280_),
    .C1(timeout_counter[27]),
    .Y(_298_)
  );
  sky130_fd_sc_hd__nand2b_1 _413_ (
    .A_N(_294_),
    .B(_298_),
    .Y(timeout_counter_nxt[27])
  );
  sky130_fd_sc_hd__nand3_1 _414_ (
    .A(timeout_counter[26]),
    .B(_280_),
    .C(_288_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__o21ai_0 _415_ (
    .A1(timeout_counter[26]),
    .A2(_288_),
    .B1(_299_),
    .Y(timeout_counter_nxt[26])
  );
  sky130_fd_sc_hd__o211ai_1 _416_ (
    .A1(timeout_counter[24]),
    .A2(_293_),
    .B1(_280_),
    .C1(timeout_counter[25]),
    .Y(_300_)
  );
  sky130_fd_sc_hd__nand2_1 _417_ (
    .A(_288_),
    .B(_300_),
    .Y(timeout_counter_nxt[25])
  );
  sky130_fd_sc_hd__nand3_1 _418_ (
    .A(timeout_counter[24]),
    .B(_280_),
    .C(_293_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__o21ai_0 _419_ (
    .A1(timeout_counter[24]),
    .A2(_293_),
    .B1(_301_),
    .Y(timeout_counter_nxt[24])
  );
  sky130_fd_sc_hd__nand2_1 _420_ (
    .A(timeout_counter[23]),
    .B(_280_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__nor4_1 _421_ (
    .A(timeout_counter[22]),
    .B(timeout_counter[21]),
    .C(timeout_counter[20]),
    .D(_292_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__o21ai_0 _422_ (
    .A1(_302_),
    .A2(_303_),
    .B1(_293_),
    .Y(timeout_counter_nxt[23])
  );
  sky130_fd_sc_hd__nand2_1 _423_ (
    .A(timeout_counter[22]),
    .B(_280_),
    .Y(_304_)
  );
  sky130_fd_sc_hd__nor3_1 _424_ (
    .A(timeout_counter[21]),
    .B(timeout_counter[20]),
    .C(_292_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__o21bai_1 _425_ (
    .A1(_304_),
    .A2(_305_),
    .B1_N(_303_),
    .Y(timeout_counter_nxt[22])
  );
  sky130_fd_sc_hd__o211ai_1 _426_ (
    .A1(timeout_counter[20]),
    .A2(_292_),
    .B1(_280_),
    .C1(timeout_counter[21]),
    .Y(_306_)
  );
  sky130_fd_sc_hd__nand2b_1 _427_ (
    .A_N(_305_),
    .B(_306_),
    .Y(timeout_counter_nxt[21])
  );
  sky130_fd_sc_hd__nand3_1 _428_ (
    .A(timeout_counter[20]),
    .B(_280_),
    .C(_292_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__o21ai_0 _429_ (
    .A1(timeout_counter[20]),
    .A2(_292_),
    .B1(_307_),
    .Y(timeout_counter_nxt[20])
  );
  sky130_fd_sc_hd__nand2_1 _430_ (
    .A(timeout_counter[19]),
    .B(_280_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__nand3b_1 _431_ (
    .A_N(timeout_counter[16]),
    .B(_238_),
    .C(_290_),
    .Y(_309_)
  );
  sky130_fd_sc_hd__nor3_1 _432_ (
    .A(timeout_counter[18]),
    .B(timeout_counter[17]),
    .C(_309_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__o21ai_0 _433_ (
    .A1(_308_),
    .A2(_310_),
    .B1(_292_),
    .Y(timeout_counter_nxt[19])
  );
  sky130_fd_sc_hd__o211ai_1 _434_ (
    .A1(timeout_counter[17]),
    .A2(_309_),
    .B1(_280_),
    .C1(timeout_counter[18]),
    .Y(_311_)
  );
  sky130_fd_sc_hd__nand2b_1 _435_ (
    .A_N(_310_),
    .B(_311_),
    .Y(timeout_counter_nxt[18])
  );
  sky130_fd_sc_hd__nand3_1 _436_ (
    .A(timeout_counter[17]),
    .B(_280_),
    .C(_309_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__o21ai_0 _437_ (
    .A1(timeout_counter[17]),
    .A2(_309_),
    .B1(_312_),
    .Y(timeout_counter_nxt[17])
  );
  sky130_fd_sc_hd__nand3_1 _438_ (
    .A(timeout_counter[16]),
    .B(_280_),
    .C(_287_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__nand2_1 _439_ (
    .A(_309_),
    .B(_313_),
    .Y(timeout_counter_nxt[16])
  );
  sky130_fd_sc_hd__nand2_1 _440_ (
    .A(timeout_counter[15]),
    .B(_280_),
    .Y(_314_)
  );
  sky130_fd_sc_hd__nand2b_1 _441_ (
    .A_N(timeout_counter[12]),
    .B(_290_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__nor3_1 _442_ (
    .A(timeout_counter[14]),
    .B(timeout_counter[13]),
    .C(_315_),
    .Y(_316_)
  );
  sky130_fd_sc_hd__o21ai_0 _443_ (
    .A1(_314_),
    .A2(_316_),
    .B1(_291_),
    .Y(timeout_counter_nxt[15])
  );
  sky130_fd_sc_hd__o211ai_1 _444_ (
    .A1(timeout_counter[13]),
    .A2(_315_),
    .B1(_280_),
    .C1(timeout_counter[14]),
    .Y(_317_)
  );
  sky130_fd_sc_hd__nand2b_1 _445_ (
    .A_N(_316_),
    .B(_317_),
    .Y(timeout_counter_nxt[14])
  );
  sky130_fd_sc_hd__nand3_1 _446_ (
    .A(timeout_counter[13]),
    .B(_280_),
    .C(_315_),
    .Y(_318_)
  );
  sky130_fd_sc_hd__o21ai_0 _447_ (
    .A1(timeout_counter[13]),
    .A2(_315_),
    .B1(_318_),
    .Y(timeout_counter_nxt[13])
  );
  sky130_fd_sc_hd__nand2_1 _448_ (
    .A(timeout_counter[12]),
    .B(_280_),
    .Y(_319_)
  );
  sky130_fd_sc_hd__o21ai_0 _449_ (
    .A1(_290_),
    .A2(_319_),
    .B1(_315_),
    .Y(timeout_counter_nxt[12])
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(timeout_counter[11]),
    .B(_280_),
    .Y(_320_)
  );
  sky130_fd_sc_hd__or3_1 _451_ (
    .A(timeout_counter[8]),
    .B(_246_),
    .C(_286_),
    .X(_321_)
  );
  sky130_fd_sc_hd__nor3_1 _452_ (
    .A(timeout_counter[10]),
    .B(timeout_counter[9]),
    .C(_321_),
    .Y(_322_)
  );
  sky130_fd_sc_hd__o21bai_1 _453_ (
    .A1(_320_),
    .A2(_322_),
    .B1_N(_290_),
    .Y(timeout_counter_nxt[11])
  );
  sky130_fd_sc_hd__nand2_1 _454_ (
    .A(timeout_counter[10]),
    .B(_280_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__mux2i_1 _455_ (
    .A0(timeout_counter[10]),
    .A1(_003_),
    .S(_296_),
    .Y(timeout_counter_nxt[10])
  );
  sky130_fd_sc_hd__nand3_1 _456_ (
    .A(timeout_counter[9]),
    .B(_280_),
    .C(_321_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _457_ (
    .A(_296_),
    .B(_004_),
    .Y(timeout_counter_nxt[9])
  );
  sky130_fd_sc_hd__o211ai_1 _458_ (
    .A1(_246_),
    .A2(_286_),
    .B1(_280_),
    .C1(timeout_counter[8]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _459_ (
    .A(_321_),
    .B(_005_),
    .Y(timeout_counter_nxt[8])
  );
  sky130_fd_sc_hd__nand3_1 _460_ (
    .A(timeout_counter[7]),
    .B(_280_),
    .C(_295_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__o21ai_0 _461_ (
    .A1(timeout_counter[7]),
    .A2(_295_),
    .B1(_006_),
    .Y(timeout_counter_nxt[7])
  );
  sky130_fd_sc_hd__o311ai_0 _462_ (
    .A1(timeout_counter[5]),
    .A2(timeout_counter[4]),
    .A3(_286_),
    .B1(_280_),
    .C1(timeout_counter[6]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _463_ (
    .A(_295_),
    .B(_007_),
    .Y(timeout_counter_nxt[6])
  );
  sky130_fd_sc_hd__o211ai_1 _464_ (
    .A1(timeout_counter[4]),
    .A2(_286_),
    .B1(_280_),
    .C1(timeout_counter[5]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__o31ai_1 _465_ (
    .A1(timeout_counter[5]),
    .A2(timeout_counter[4]),
    .A3(_286_),
    .B1(_008_),
    .Y(timeout_counter_nxt[5])
  );
  sky130_fd_sc_hd__nand3_1 _466_ (
    .A(timeout_counter[4]),
    .B(_280_),
    .C(_286_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__o21ai_0 _467_ (
    .A1(timeout_counter[4]),
    .A2(_286_),
    .B1(_009_),
    .Y(timeout_counter_nxt[4])
  );
  sky130_fd_sc_hd__a31o_1 _468_ (
    .A1(timeout_counter[3]),
    .A2(_280_),
    .A3(_284_),
    .B1(_285_),
    .X(timeout_counter_nxt[3])
  );
  sky130_fd_sc_hd__o211ai_1 _469_ (
    .A1(timeout_counter[1]),
    .A2(_283_),
    .B1(_280_),
    .C1(timeout_counter[2]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _470_ (
    .A(_284_),
    .B(_010_),
    .Y(timeout_counter_nxt[2])
  );
  sky130_fd_sc_hd__nand3_1 _471_ (
    .A(timeout_counter[1]),
    .B(_280_),
    .C(_283_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__o21ai_0 _472_ (
    .A1(timeout_counter[1]),
    .A2(_283_),
    .B1(_011_),
    .Y(timeout_counter_nxt[1])
  );
  sky130_fd_sc_hd__nand2_1 _473_ (
    .A(timeout_counter[0]),
    .B(_277_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand3_1 _474_ (
    .A(_280_),
    .B(_283_),
    .C(_012_),
    .Y(timeout_counter_nxt[0])
  );
  sky130_fd_sc_hd__o21ai_0 _475_ (
    .A1(_265_),
    .A2(_266_),
    .B1(s_axi_arvalid),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _476_ (
    .A(_013_),
    .Y(s_axi_arready)
  );
  sky130_fd_sc_hd__nor2_1 _477_ (
    .A(state[1]),
    .B(_228_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__o21ai_0 _478_ (
    .A1(_263_),
    .A2(_014_),
    .B1(s_axi_awvalid),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand3_1 _479_ (
    .A(_269_),
    .B(_272_),
    .C(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _480_ (
    .A(s_axi_awaddr[30]),
    .B(_016_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2b_1 _481_ (
    .A_N(_217_),
    .B(_259_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__o21ai_0 _482_ (
    .A1(_214_),
    .A2(bridge_state[2]),
    .B1(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _483_ (
    .A(SADDR[30]),
    .B(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _484_ (
    .A(s_axi_araddr[30]),
    .B(_013_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a31oi_1 _485_ (
    .A1(_013_),
    .A2(_017_),
    .A3(_020_),
    .B1(_021_),
    .Y(captured_addr_nxt[30])
  );
  sky130_fd_sc_hd__nand2_1 _486_ (
    .A(s_axi_awaddr[29]),
    .B(_016_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _487_ (
    .A(SADDR[29]),
    .B(_019_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _488_ (
    .A(s_axi_araddr[29]),
    .B(_013_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a31oi_1 _489_ (
    .A1(_013_),
    .A2(_022_),
    .A3(_023_),
    .B1(_024_),
    .Y(captured_addr_nxt[29])
  );
  sky130_fd_sc_hd__nand2_1 _490_ (
    .A(s_axi_awaddr[28]),
    .B(_016_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _491_ (
    .A(SADDR[28]),
    .B(_019_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _492_ (
    .A(s_axi_araddr[28]),
    .B(_013_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a31oi_1 _493_ (
    .A1(_013_),
    .A2(_025_),
    .A3(_026_),
    .B1(_027_),
    .Y(captured_addr_nxt[28])
  );
  sky130_fd_sc_hd__nand2_1 _494_ (
    .A(s_axi_awaddr[27]),
    .B(_016_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _495_ (
    .A(SADDR[27]),
    .B(_019_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor2_1 _496_ (
    .A(s_axi_araddr[27]),
    .B(_013_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a31oi_1 _497_ (
    .A1(_013_),
    .A2(_028_),
    .A3(_029_),
    .B1(_030_),
    .Y(captured_addr_nxt[27])
  );
  sky130_fd_sc_hd__nand2_1 _498_ (
    .A(s_axi_awaddr[26]),
    .B(_016_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _499_ (
    .A(SADDR[26]),
    .B(_019_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _500_ (
    .A(s_axi_araddr[26]),
    .B(_013_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a31oi_1 _501_ (
    .A1(_013_),
    .A2(_031_),
    .A3(_032_),
    .B1(_033_),
    .Y(captured_addr_nxt[26])
  );
  sky130_fd_sc_hd__nand2_1 _502_ (
    .A(s_axi_awaddr[25]),
    .B(_016_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _503_ (
    .A(SADDR[25]),
    .B(_019_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor2_1 _504_ (
    .A(s_axi_araddr[25]),
    .B(_013_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a31oi_1 _505_ (
    .A1(_013_),
    .A2(_034_),
    .A3(_035_),
    .B1(_036_),
    .Y(captured_addr_nxt[25])
  );
  sky130_fd_sc_hd__nand2_1 _506_ (
    .A(s_axi_awaddr[24]),
    .B(_016_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _507_ (
    .A(SADDR[24]),
    .B(_019_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _508_ (
    .A(s_axi_araddr[24]),
    .B(_013_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a31oi_1 _509_ (
    .A1(_013_),
    .A2(_037_),
    .A3(_038_),
    .B1(_039_),
    .Y(captured_addr_nxt[24])
  );
  sky130_fd_sc_hd__nand2_1 _510_ (
    .A(s_axi_awaddr[23]),
    .B(_016_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _511_ (
    .A(SADDR[23]),
    .B(_019_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor2_1 _512_ (
    .A(s_axi_araddr[23]),
    .B(_013_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a31oi_1 _513_ (
    .A1(_013_),
    .A2(_040_),
    .A3(_041_),
    .B1(_042_),
    .Y(captured_addr_nxt[23])
  );
  sky130_fd_sc_hd__nand2_1 _514_ (
    .A(s_axi_awaddr[22]),
    .B(_016_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _515_ (
    .A(SADDR[22]),
    .B(_019_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_1 _516_ (
    .A(s_axi_araddr[22]),
    .B(_013_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a31oi_1 _517_ (
    .A1(_013_),
    .A2(_043_),
    .A3(_044_),
    .B1(_045_),
    .Y(captured_addr_nxt[22])
  );
  sky130_fd_sc_hd__nand2_1 _518_ (
    .A(s_axi_awaddr[21]),
    .B(_016_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _519_ (
    .A(SADDR[21]),
    .B(_019_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _520_ (
    .A(s_axi_araddr[21]),
    .B(_013_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a31oi_1 _521_ (
    .A1(_013_),
    .A2(_046_),
    .A3(_047_),
    .B1(_048_),
    .Y(captured_addr_nxt[21])
  );
  sky130_fd_sc_hd__nand2_1 _522_ (
    .A(s_axi_awaddr[20]),
    .B(_016_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _523_ (
    .A(SADDR[20]),
    .B(_019_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _524_ (
    .A(s_axi_araddr[20]),
    .B(_013_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a31oi_1 _525_ (
    .A1(_013_),
    .A2(_049_),
    .A3(_050_),
    .B1(_051_),
    .Y(captured_addr_nxt[20])
  );
  sky130_fd_sc_hd__nand2_1 _526_ (
    .A(s_axi_awaddr[19]),
    .B(_016_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _527_ (
    .A(SADDR[19]),
    .B(_019_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _528_ (
    .A(s_axi_araddr[19]),
    .B(_013_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a31oi_1 _529_ (
    .A1(_013_),
    .A2(_052_),
    .A3(_053_),
    .B1(_054_),
    .Y(captured_addr_nxt[19])
  );
  sky130_fd_sc_hd__nand2_1 _530_ (
    .A(s_axi_awaddr[18]),
    .B(_016_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _531_ (
    .A(SADDR[18]),
    .B(_019_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor2_1 _532_ (
    .A(s_axi_araddr[18]),
    .B(_013_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a31oi_1 _533_ (
    .A1(_013_),
    .A2(_055_),
    .A3(_056_),
    .B1(_057_),
    .Y(captured_addr_nxt[18])
  );
  sky130_fd_sc_hd__nand2_1 _534_ (
    .A(s_axi_awaddr[17]),
    .B(_016_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _535_ (
    .A(SADDR[17]),
    .B(_019_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _536_ (
    .A(s_axi_araddr[17]),
    .B(_013_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a31oi_1 _537_ (
    .A1(_013_),
    .A2(_058_),
    .A3(_059_),
    .B1(_060_),
    .Y(captured_addr_nxt[17])
  );
  sky130_fd_sc_hd__nand2_1 _538_ (
    .A(s_axi_awaddr[16]),
    .B(_016_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _539_ (
    .A(SADDR[16]),
    .B(_019_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _540_ (
    .A(s_axi_araddr[16]),
    .B(_013_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a31oi_1 _541_ (
    .A1(_013_),
    .A2(_061_),
    .A3(_062_),
    .B1(_063_),
    .Y(captured_addr_nxt[16])
  );
  sky130_fd_sc_hd__nand2_1 _542_ (
    .A(s_axi_awaddr[15]),
    .B(_016_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _543_ (
    .A(SADDR[15]),
    .B(_019_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor2_1 _544_ (
    .A(s_axi_araddr[15]),
    .B(_013_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a31oi_1 _545_ (
    .A1(_013_),
    .A2(_064_),
    .A3(_065_),
    .B1(_066_),
    .Y(captured_addr_nxt[15])
  );
  sky130_fd_sc_hd__nand2_1 _546_ (
    .A(s_axi_awaddr[14]),
    .B(_016_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _547_ (
    .A(SADDR[14]),
    .B(_019_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _548_ (
    .A(s_axi_araddr[14]),
    .B(_013_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a31oi_1 _549_ (
    .A1(_013_),
    .A2(_067_),
    .A3(_068_),
    .B1(_069_),
    .Y(captured_addr_nxt[14])
  );
  sky130_fd_sc_hd__nand2_1 _550_ (
    .A(s_axi_awaddr[13]),
    .B(_016_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _551_ (
    .A(SADDR[13]),
    .B(_019_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _552_ (
    .A(s_axi_araddr[13]),
    .B(_013_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a31oi_1 _553_ (
    .A1(_013_),
    .A2(_070_),
    .A3(_071_),
    .B1(_072_),
    .Y(captured_addr_nxt[13])
  );
  sky130_fd_sc_hd__nand2_1 _554_ (
    .A(s_axi_awaddr[12]),
    .B(_016_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _555_ (
    .A(SADDR[12]),
    .B(_019_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _556_ (
    .A(s_axi_araddr[12]),
    .B(_013_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a31oi_1 _557_ (
    .A1(_013_),
    .A2(_073_),
    .A3(_074_),
    .B1(_075_),
    .Y(captured_addr_nxt[12])
  );
  sky130_fd_sc_hd__nand2_1 _558_ (
    .A(s_axi_awaddr[11]),
    .B(_016_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _559_ (
    .A(SADDR[11]),
    .B(_019_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _560_ (
    .A(s_axi_araddr[11]),
    .B(_013_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a31oi_1 _561_ (
    .A1(_013_),
    .A2(_076_),
    .A3(_077_),
    .B1(_078_),
    .Y(captured_addr_nxt[11])
  );
  sky130_fd_sc_hd__nand2_1 _562_ (
    .A(s_axi_awaddr[10]),
    .B(_016_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _563_ (
    .A(SADDR[10]),
    .B(_019_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _564_ (
    .A(s_axi_araddr[10]),
    .B(_013_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a31oi_1 _565_ (
    .A1(_013_),
    .A2(_079_),
    .A3(_080_),
    .B1(_081_),
    .Y(captured_addr_nxt[10])
  );
  sky130_fd_sc_hd__nand2_1 _566_ (
    .A(s_axi_awaddr[9]),
    .B(_016_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _567_ (
    .A(SADDR[9]),
    .B(_019_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _568_ (
    .A(s_axi_araddr[9]),
    .B(_013_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a31oi_1 _569_ (
    .A1(_013_),
    .A2(_082_),
    .A3(_083_),
    .B1(_084_),
    .Y(captured_addr_nxt[9])
  );
  sky130_fd_sc_hd__nand2_1 _570_ (
    .A(s_axi_awaddr[8]),
    .B(_016_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _571_ (
    .A(SADDR[8]),
    .B(_019_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor2_1 _572_ (
    .A(s_axi_araddr[8]),
    .B(_013_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a31oi_1 _573_ (
    .A1(_013_),
    .A2(_085_),
    .A3(_086_),
    .B1(_087_),
    .Y(captured_addr_nxt[8])
  );
  sky130_fd_sc_hd__nand2_1 _574_ (
    .A(s_axi_awaddr[7]),
    .B(_016_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _575_ (
    .A(SADDR[7]),
    .B(_019_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor2_1 _576_ (
    .A(s_axi_araddr[7]),
    .B(_013_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a31oi_1 _577_ (
    .A1(_013_),
    .A2(_088_),
    .A3(_089_),
    .B1(_090_),
    .Y(captured_addr_nxt[7])
  );
  sky130_fd_sc_hd__nand2_1 _578_ (
    .A(s_axi_awaddr[6]),
    .B(_016_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_1 _579_ (
    .A(SADDR[6]),
    .B(_019_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _580_ (
    .A(s_axi_araddr[6]),
    .B(_013_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a31oi_1 _581_ (
    .A1(_013_),
    .A2(_091_),
    .A3(_092_),
    .B1(_093_),
    .Y(captured_addr_nxt[6])
  );
  sky130_fd_sc_hd__nand2_1 _582_ (
    .A(s_axi_awaddr[5]),
    .B(_016_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _583_ (
    .A(SADDR[5]),
    .B(_019_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor2_1 _584_ (
    .A(s_axi_araddr[5]),
    .B(_013_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a31oi_1 _585_ (
    .A1(_013_),
    .A2(_094_),
    .A3(_095_),
    .B1(_096_),
    .Y(captured_addr_nxt[5])
  );
  sky130_fd_sc_hd__nand2_1 _586_ (
    .A(s_axi_awaddr[4]),
    .B(_016_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _587_ (
    .A(SADDR[4]),
    .B(_019_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor2_1 _588_ (
    .A(s_axi_araddr[4]),
    .B(_013_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a31oi_1 _589_ (
    .A1(_013_),
    .A2(_097_),
    .A3(_098_),
    .B1(_099_),
    .Y(captured_addr_nxt[4])
  );
  sky130_fd_sc_hd__nand2_1 _590_ (
    .A(s_axi_awaddr[3]),
    .B(_016_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _591_ (
    .A(SADDR[3]),
    .B(_019_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2_1 _592_ (
    .A(s_axi_araddr[3]),
    .B(_013_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a31oi_1 _593_ (
    .A1(_013_),
    .A2(_100_),
    .A3(_101_),
    .B1(_102_),
    .Y(captured_addr_nxt[3])
  );
  sky130_fd_sc_hd__nand2_1 _594_ (
    .A(s_axi_awaddr[2]),
    .B(_016_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _595_ (
    .A(SADDR[2]),
    .B(_019_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor2_1 _596_ (
    .A(s_axi_araddr[2]),
    .B(_013_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a31oi_1 _597_ (
    .A1(_013_),
    .A2(_103_),
    .A3(_104_),
    .B1(_105_),
    .Y(captured_addr_nxt[2])
  );
  sky130_fd_sc_hd__nand2_1 _598_ (
    .A(s_axi_awaddr[1]),
    .B(_016_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _599_ (
    .A(SADDR[1]),
    .B(_019_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor2_1 _600_ (
    .A(s_axi_araddr[1]),
    .B(_013_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a31oi_1 _601_ (
    .A1(_013_),
    .A2(_106_),
    .A3(_107_),
    .B1(_108_),
    .Y(captured_addr_nxt[1])
  );
  sky130_fd_sc_hd__nand2_1 _602_ (
    .A(s_axi_awaddr[0]),
    .B(_016_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _603_ (
    .A(SADDR[0]),
    .B(_019_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _604_ (
    .A(s_axi_araddr[0]),
    .B(_013_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a31oi_1 _605_ (
    .A1(_013_),
    .A2(_109_),
    .A3(_110_),
    .B1(_111_),
    .Y(captured_addr_nxt[0])
  );
  sky130_fd_sc_hd__nand2_1 _606_ (
    .A(write_happened),
    .B(_226_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor2_1 _607_ (
    .A(s_axi_bready),
    .B(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__and2_0 _608_ (
    .A(write_resp[0]),
    .B(_113_),
    .X(write_resp_nxt[0])
  );
  sky130_fd_sc_hd__nor3_1 _609_ (
    .A(bridge_state[2]),
    .B(_215_),
    .C(_230_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__o21ai_0 _610_ (
    .A1(_265_),
    .A2(_014_),
    .B1(s_axi_wvalid),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o21ai_0 _611_ (
    .A1(_215_),
    .A2(_264_),
    .B1(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o21ai_0 _612_ (
    .A1(_114_),
    .A2(_116_),
    .B1(s_axi_wdata[0]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__o21ai_0 _613_ (
    .A1(_232_),
    .A2(_261_),
    .B1(_268_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__o21ai_0 _614_ (
    .A1(_275_),
    .A2(_118_),
    .B1(SWDATA[0]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _615_ (
    .A(_117_),
    .B(_119_),
    .Y(axi_write_data_nxt)
  );
  sky130_fd_sc_hd__nand2_1 _616_ (
    .A(_261_),
    .B(_112_),
    .Y(SWRT)
  );
  sky130_fd_sc_hd__nor2_1 _617_ (
    .A(_221_),
    .B(SWRT),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor2_1 _618_ (
    .A(s_axi_rready),
    .B(_223_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _619_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[30]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a21oi_1 _620_ (
    .A1(read_data_reg[30]),
    .A2(_121_),
    .B1(_120_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a21oi_1 _621_ (
    .A1(_120_),
    .A2(_122_),
    .B1(_123_),
    .Y(read_data_nxt[30])
  );
  sky130_fd_sc_hd__nand2_1 _622_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[29]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__a21oi_1 _623_ (
    .A1(read_data_reg[29]),
    .A2(_121_),
    .B1(_120_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a21oi_1 _624_ (
    .A1(_120_),
    .A2(_124_),
    .B1(_125_),
    .Y(read_data_nxt[29])
  );
  sky130_fd_sc_hd__nand2_1 _625_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[28]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a21oi_1 _626_ (
    .A1(read_data_reg[28]),
    .A2(_121_),
    .B1(_120_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a21oi_1 _627_ (
    .A1(_120_),
    .A2(_126_),
    .B1(_127_),
    .Y(read_data_nxt[28])
  );
  sky130_fd_sc_hd__nand2_1 _628_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[27]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a21oi_1 _629_ (
    .A1(read_data_reg[27]),
    .A2(_121_),
    .B1(_120_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a21oi_1 _630_ (
    .A1(_120_),
    .A2(_128_),
    .B1(_129_),
    .Y(read_data_nxt[27])
  );
  sky130_fd_sc_hd__nand2_1 _631_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[26]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a21oi_1 _632_ (
    .A1(read_data_reg[26]),
    .A2(_121_),
    .B1(_120_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a21oi_1 _633_ (
    .A1(_120_),
    .A2(_130_),
    .B1(_131_),
    .Y(read_data_nxt[26])
  );
  sky130_fd_sc_hd__nand2_1 _634_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[25]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a21oi_1 _635_ (
    .A1(read_data_reg[25]),
    .A2(_121_),
    .B1(_120_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a21oi_1 _636_ (
    .A1(_120_),
    .A2(_132_),
    .B1(_133_),
    .Y(read_data_nxt[25])
  );
  sky130_fd_sc_hd__nand2_1 _637_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[24]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _638_ (
    .A1(read_data_reg[24]),
    .A2(_121_),
    .B1(_120_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a21oi_1 _639_ (
    .A1(_120_),
    .A2(_134_),
    .B1(_135_),
    .Y(read_data_nxt[24])
  );
  sky130_fd_sc_hd__nand2_1 _640_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[23]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a21oi_1 _641_ (
    .A1(read_data_reg[23]),
    .A2(_121_),
    .B1(_120_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a21oi_1 _642_ (
    .A1(_120_),
    .A2(_136_),
    .B1(_137_),
    .Y(read_data_nxt[23])
  );
  sky130_fd_sc_hd__nand2_1 _643_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[22]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a21oi_1 _644_ (
    .A1(read_data_reg[22]),
    .A2(_121_),
    .B1(_120_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a21oi_1 _645_ (
    .A1(_120_),
    .A2(_138_),
    .B1(_139_),
    .Y(read_data_nxt[22])
  );
  sky130_fd_sc_hd__nand2_1 _646_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[21]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a21oi_1 _647_ (
    .A1(read_data_reg[21]),
    .A2(_121_),
    .B1(_120_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a21oi_1 _648_ (
    .A1(_120_),
    .A2(_140_),
    .B1(_141_),
    .Y(read_data_nxt[21])
  );
  sky130_fd_sc_hd__nand2_1 _649_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[20]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _650_ (
    .A1(read_data_reg[20]),
    .A2(_121_),
    .B1(_120_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a21oi_1 _651_ (
    .A1(_120_),
    .A2(_142_),
    .B1(_143_),
    .Y(read_data_nxt[20])
  );
  sky130_fd_sc_hd__nand2_1 _652_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[19]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a21oi_1 _653_ (
    .A1(read_data_reg[19]),
    .A2(_121_),
    .B1(_120_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a21oi_1 _654_ (
    .A1(_120_),
    .A2(_144_),
    .B1(_145_),
    .Y(read_data_nxt[19])
  );
  sky130_fd_sc_hd__nand2_1 _655_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[18]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a21oi_1 _656_ (
    .A1(read_data_reg[18]),
    .A2(_121_),
    .B1(_120_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a21oi_1 _657_ (
    .A1(_120_),
    .A2(_146_),
    .B1(_147_),
    .Y(read_data_nxt[18])
  );
  sky130_fd_sc_hd__nand2_1 _658_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[17]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a21oi_1 _659_ (
    .A1(read_data_reg[17]),
    .A2(_121_),
    .B1(_120_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__a21oi_1 _660_ (
    .A1(_120_),
    .A2(_148_),
    .B1(_149_),
    .Y(read_data_nxt[17])
  );
  sky130_fd_sc_hd__nand2_1 _661_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[16]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a21oi_1 _662_ (
    .A1(read_data_reg[16]),
    .A2(_121_),
    .B1(_120_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a21oi_1 _663_ (
    .A1(_120_),
    .A2(_150_),
    .B1(_151_),
    .Y(read_data_nxt[16])
  );
  sky130_fd_sc_hd__nand2_1 _664_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[15]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__a21oi_1 _665_ (
    .A1(read_data_reg[15]),
    .A2(_121_),
    .B1(_120_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21oi_1 _666_ (
    .A1(_120_),
    .A2(_152_),
    .B1(_153_),
    .Y(read_data_nxt[15])
  );
  sky130_fd_sc_hd__nand2_1 _667_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[14]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a21oi_1 _668_ (
    .A1(read_data_reg[14]),
    .A2(_121_),
    .B1(_120_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a21oi_1 _669_ (
    .A1(_120_),
    .A2(_154_),
    .B1(_155_),
    .Y(read_data_nxt[14])
  );
  sky130_fd_sc_hd__nand2_1 _670_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[13]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a21oi_1 _671_ (
    .A1(read_data_reg[13]),
    .A2(_121_),
    .B1(_120_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a21oi_1 _672_ (
    .A1(_120_),
    .A2(_156_),
    .B1(_157_),
    .Y(read_data_nxt[13])
  );
  sky130_fd_sc_hd__nand2_1 _673_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[12]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a21oi_1 _674_ (
    .A1(read_data_reg[12]),
    .A2(_121_),
    .B1(_120_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a21oi_1 _675_ (
    .A1(_120_),
    .A2(_158_),
    .B1(_159_),
    .Y(read_data_nxt[12])
  );
  sky130_fd_sc_hd__nand2_1 _676_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[11]),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a21oi_1 _677_ (
    .A1(read_data_reg[11]),
    .A2(_121_),
    .B1(_120_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a21oi_1 _678_ (
    .A1(_120_),
    .A2(_160_),
    .B1(_161_),
    .Y(read_data_nxt[11])
  );
  sky130_fd_sc_hd__nand2_1 _679_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[10]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__a21oi_1 _680_ (
    .A1(read_data_reg[10]),
    .A2(_121_),
    .B1(_120_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a21oi_1 _681_ (
    .A1(_120_),
    .A2(_162_),
    .B1(_163_),
    .Y(read_data_nxt[10])
  );
  sky130_fd_sc_hd__nand2_1 _682_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[9]),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a21oi_1 _683_ (
    .A1(read_data_reg[9]),
    .A2(_121_),
    .B1(_120_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__a21oi_1 _684_ (
    .A1(_120_),
    .A2(_164_),
    .B1(_165_),
    .Y(read_data_nxt[9])
  );
  sky130_fd_sc_hd__nand2_1 _685_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[8]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a21oi_1 _686_ (
    .A1(read_data_reg[8]),
    .A2(_121_),
    .B1(_120_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__a21oi_1 _687_ (
    .A1(_120_),
    .A2(_166_),
    .B1(_167_),
    .Y(read_data_nxt[8])
  );
  sky130_fd_sc_hd__nand2_1 _688_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[7]),
    .Y(_168_)
  );
  sky130_fd_sc_hd__a21oi_1 _689_ (
    .A1(read_data_reg[7]),
    .A2(_121_),
    .B1(_120_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a21oi_1 _690_ (
    .A1(_120_),
    .A2(_168_),
    .B1(_169_),
    .Y(read_data_nxt[7])
  );
  sky130_fd_sc_hd__nand2_1 _691_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[6]),
    .Y(_170_)
  );
  sky130_fd_sc_hd__a21oi_1 _692_ (
    .A1(read_data_reg[6]),
    .A2(_121_),
    .B1(_120_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__a21oi_1 _693_ (
    .A1(_120_),
    .A2(_170_),
    .B1(_171_),
    .Y(read_data_nxt[6])
  );
  sky130_fd_sc_hd__nand2_1 _694_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[5]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a21oi_1 _695_ (
    .A1(read_data_reg[5]),
    .A2(_121_),
    .B1(_120_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a21oi_1 _696_ (
    .A1(_120_),
    .A2(_172_),
    .B1(_173_),
    .Y(read_data_nxt[5])
  );
  sky130_fd_sc_hd__nand2_1 _697_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[4]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__a21oi_1 _698_ (
    .A1(read_data_reg[4]),
    .A2(_121_),
    .B1(_120_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__a21oi_1 _699_ (
    .A1(_120_),
    .A2(_174_),
    .B1(_175_),
    .Y(read_data_nxt[4])
  );
  sky130_fd_sc_hd__nand2_1 _700_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[3]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__a21oi_1 _701_ (
    .A1(read_data_reg[3]),
    .A2(_121_),
    .B1(_120_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__a21oi_1 _702_ (
    .A1(_120_),
    .A2(_176_),
    .B1(_177_),
    .Y(read_data_nxt[3])
  );
  sky130_fd_sc_hd__nand2_1 _703_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[2]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__a21oi_1 _704_ (
    .A1(read_data_reg[2]),
    .A2(_121_),
    .B1(_120_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a21oi_1 _705_ (
    .A1(_120_),
    .A2(_178_),
    .B1(_179_),
    .Y(read_data_nxt[2])
  );
  sky130_fd_sc_hd__nand2_1 _706_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[1]),
    .Y(_180_)
  );
  sky130_fd_sc_hd__a21oi_1 _707_ (
    .A1(read_data_reg[1]),
    .A2(_121_),
    .B1(_120_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__a21oi_1 _708_ (
    .A1(_120_),
    .A2(_180_),
    .B1(_181_),
    .Y(read_data_nxt[1])
  );
  sky130_fd_sc_hd__nand2_1 _709_ (
    .A(m_apb_psel),
    .B(m_apb_prdata[0]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__a21oi_1 _710_ (
    .A1(read_data_reg[0]),
    .A2(_121_),
    .B1(_120_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__a21oi_1 _711_ (
    .A1(_120_),
    .A2(_182_),
    .B1(_183_),
    .Y(read_data_nxt[0])
  );
  sky130_fd_sc_hd__and2_0 _712_ (
    .A(read_resp[0]),
    .B(_121_),
    .X(read_resp_nxt[0])
  );
  sky130_fd_sc_hd__a21boi_0 _713_ (
    .A1(_257_),
    .A2(_276_),
    .B1_N(s_axi_aresetn),
    .Y(apb_reset)
  );
  sky130_fd_sc_hd__or3_1 _714_ (
    .A(s_axi_arvalid),
    .B(_215_),
    .C(s_axi_awvalid),
    .X(_184_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _715_ (
    .A1_N(_222_),
    .A2_N(_224_),
    .B1(_184_),
    .B2(s_axi_rready),
    .Y(_185_)
  );
  sky130_fd_sc_hd__o221ai_1 _716_ (
    .A1(s_axi_awvalid),
    .A2(_268_),
    .B1(_184_),
    .B2(_228_),
    .C1(_270_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nor2_1 _717_ (
    .A(_185_),
    .B(_186_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nand2_1 _718_ (
    .A(_257_),
    .B(_274_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _719_ (
    .A(_187_),
    .B(_188_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__or4_1 _720_ (
    .A(SADDR[5]),
    .B(SADDR[4]),
    .C(SADDR[2]),
    .D(SADDR[1]),
    .X(_189_)
  );
  sky130_fd_sc_hd__o31a_1 _721_ (
    .A1(SADDR[3]),
    .A2(SADDR[0]),
    .A3(_189_),
    .B1(SADDR[6]),
    .X(_190_)
  );
  sky130_fd_sc_hd__nor4_1 _722_ (
    .A(SADDR[12]),
    .B(SADDR[11]),
    .C(SADDR[10]),
    .D(SADDR[9]),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nor4_1 _723_ (
    .A(SADDR[16]),
    .B(SADDR[15]),
    .C(SADDR[14]),
    .D(SADDR[13]),
    .Y(_192_)
  );
  sky130_fd_sc_hd__a2111oi_0 _724_ (
    .A1(_218_),
    .A2(_232_),
    .B1(SADDR[8]),
    .C1(SADDR[7]),
    .D1(SADDR[31]),
    .Y(_193_)
  );
  sky130_fd_sc_hd__nand3_1 _725_ (
    .A(_191_),
    .B(_192_),
    .C(_193_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nor4_1 _726_ (
    .A(SADDR[20]),
    .B(SADDR[19]),
    .C(SADDR[18]),
    .D(SADDR[17]),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nor3_1 _727_ (
    .A(SADDR[24]),
    .B(SADDR[23]),
    .C(SADDR[22]),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nor4_1 _728_ (
    .A(SADDR[30]),
    .B(SADDR[29]),
    .C(SADDR[28]),
    .D(SADDR[25]),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nor3_1 _729_ (
    .A(SADDR[27]),
    .B(SADDR[26]),
    .C(SADDR[21]),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nand4_1 _730_ (
    .A(_195_),
    .B(_196_),
    .C(_197_),
    .D(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nor3_1 _731_ (
    .A(_190_),
    .B(_194_),
    .C(_199_),
    .Y(SSEL)
  );
  sky130_fd_sc_hd__nand2_1 _732_ (
    .A(s_axi_awvalid),
    .B(_116_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _733_ (
    .A(_269_),
    .SLEEP(_114_),
    .X(_201_)
  );
  sky130_fd_sc_hd__nand3_1 _734_ (
    .A(_013_),
    .B(_200_),
    .C(_201_),
    .Y(STREQ)
  );
  sky130_fd_sc_hd__nand3_1 _735_ (
    .A(_268_),
    .B(_272_),
    .C(_015_),
    .Y(s_axi_awready)
  );
  sky130_fd_sc_hd__o21ai_0 _736_ (
    .A1(bridge_state[2]),
    .A2(_230_),
    .B1(_115_),
    .Y(s_axi_wready)
  );
  sky130_fd_sc_hd__nor2_1 _737_ (
    .A(_120_),
    .B(_121_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nand2_1 _738_ (
    .A(_188_),
    .B(_202_),
    .Y(read_valid_nxt)
  );
  sky130_fd_sc_hd__nand2_1 _739_ (
    .A(_257_),
    .B(_275_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nor2_1 _740_ (
    .A(_279_),
    .B(_113_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nand2_1 _741_ (
    .A(_203_),
    .B(_204_),
    .Y(write_resp_valid_nxt)
  );
  sky130_fd_sc_hd__a32oi_1 _742_ (
    .A1(m_apb_psel),
    .A2(m_apb_pslverr),
    .A3(_222_),
    .B1(_121_),
    .B2(read_resp[1]),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nand2_1 _743_ (
    .A(_188_),
    .B(_205_),
    .Y(read_resp_nxt[1])
  );
  sky130_fd_sc_hd__nand2_1 _744_ (
    .A(read_data_reg[31]),
    .B(_121_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__nand2_1 _745_ (
    .A(m_apb_prdata[31]),
    .B(_120_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__o21ai_0 _746_ (
    .A1(_120_),
    .A2(_206_),
    .B1(_207_),
    .Y(read_data_nxt[31])
  );
  sky130_fd_sc_hd__a32oi_1 _747_ (
    .A1(m_apb_psel),
    .A2(m_apb_pslverr),
    .A3(_279_),
    .B1(_113_),
    .B2(write_resp[1]),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nand2_1 _748_ (
    .A(_203_),
    .B(_208_),
    .Y(write_resp_nxt[1])
  );
  sky130_fd_sc_hd__nand2_1 _749_ (
    .A(s_axi_awaddr[31]),
    .B(_016_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand2_1 _750_ (
    .A(SADDR[31]),
    .B(_019_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nor2_1 _751_ (
    .A(s_axi_araddr[31]),
    .B(_013_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__a31oi_1 _752_ (
    .A1(_013_),
    .A2(_209_),
    .A3(_210_),
    .B1(_211_),
    .Y(captured_addr_nxt[31])
  );
  sky130_fd_sc_hd__nand2_1 _753_ (
    .A(timeout_counter[31]),
    .B(_280_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__a21oi_1 _754_ (
    .A1(_256_),
    .A2(_276_),
    .B1(_212_),
    .Y(timeout_counter_nxt[31])
  );
  sky130_fd_sc_hd__o21ai_0 _755_ (
    .A1(s_axi_bready),
    .A2(_112_),
    .B1(_261_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__and2_0 _756_ (
    .A(s_axi_aresetn),
    .B(_213_),
    .X(write_happened_nxt)
  );
  (* src = "axi_apb_bridge.v:274.1-342.4" *)
  sky130_fd_sc_hd__dfrtp_1 _757_ (
    .CLK(s_axi_clk),
    .D(_001_),
    .Q(bridge_state[0]),
    .RESET_B(s_axi_aresetn)
  );
  (* src = "axi_apb_bridge.v:274.1-342.4" *)
  sky130_fd_sc_hd__dfrtp_1 _758_ (
    .CLK(s_axi_clk),
    .D(_000_),
    .Q(bridge_state[1]),
    .RESET_B(s_axi_aresetn)
  );
  (* src = "axi_apb_bridge.v:274.1-342.4" *)
  sky130_fd_sc_hd__dfrtp_1 _759_ (
    .CLK(s_axi_clk),
    .D(_002_),
    .Q(bridge_state[2]),
    .RESET_B(s_axi_aresetn)
  );
  (* src = "axi_apb_bridge.v:142.3-145.119" *)
  \$paramod\apb_master\c_apb_num_slaves=s32'00000000000000000000000000000001  UUT (
    .Out_State(state),
    .PADDR(m_apb_paddr),
    .PCLK(s_axi_clk),
    .PENABLE(m_apb_penable),
    .PPROT(3'h0),
    .PRDATA(m_apb_prdata),
    .PREADY(m_apb_pready),
    .PRESETn(apb_reset),
    .PSELx(m_apb_psel),
    .PSLVERR(m_apb_pslverr),
    .PSTRB(m_apb_pstrb),
    .PWDATA(m_apb_pwdata),
    .PWRITE(m_apb_pwrite),
    .SADDR(SADDR),
    .SRDATA(SRDATA),
    .SSEL(SSEL),
    .STREQ(STREQ),
    .SWDATA(SWDATA),
    .SWRT(SWRT),
    .m_apb_prdata10(m_apb_prdata10),
    .m_apb_prdata11(m_apb_prdata11),
    .m_apb_prdata12(m_apb_prdata12),
    .m_apb_prdata13(m_apb_prdata13),
    .m_apb_prdata14(m_apb_prdata14),
    .m_apb_prdata15(m_apb_prdata15),
    .m_apb_prdata16(m_apb_prdata16),
    .m_apb_prdata2(m_apb_prdata2),
    .m_apb_prdata3(m_apb_prdata3),
    .m_apb_prdata4(m_apb_prdata4),
    .m_apb_prdata5(m_apb_prdata5),
    .m_apb_prdata6(m_apb_prdata6),
    .m_apb_prdata7(m_apb_prdata7),
    .m_apb_prdata8(m_apb_prdata8),
    .m_apb_prdata9(m_apb_prdata9)
  );
  (* src = "axi_apb_bridge.v:82.2-82.82" *)
  \$paramod\flop\width=s32'00000000000000000000000000100000  axi_write_data_ff (
    .clk(s_axi_clk),
    .d({ 31'h00000000, axi_write_data_nxt }),
    .q(SWDATA),
    .rst(s_axi_aresetn)
  );
  (* src = "axi_apb_bridge.v:108.2-108.75" *)
  \$paramod\flop\width=s32'00000000000000000000000000100000  captured_addr_ff (
    .clk(s_axi_clk),
    .d(captured_addr_nxt),
    .q(SADDR),
    .rst(s_axi_aresetn)
  );
  (* src = "axi_apb_bridge.v:102.2-102.67" *)
  \$paramod\flop\width=s32'00000000000000000000000000100000  read_data_ff (
    .clk(s_axi_clk),
    .d(read_data_nxt),
    .q(read_data_reg),
    .rst(s_axi_aresetn)
  );
  (* src = "axi_apb_bridge.v:113.2-113.63" *)
  \$paramod\flop\width=s32'00000000000000000000000000000010  read_resp_ff (
    .clk(s_axi_clk),
    .d(read_resp_nxt),
    .q(read_resp),
    .rst(s_axi_aresetn)
  );
  (* src = "axi_apb_bridge.v:92.2-92.70" *)
  \$paramod\flop\width=s32'00000000000000000000000000000001  read_valid_ff (
    .clk(s_axi_clk),
    .d(read_valid_nxt),
    .q(read_valid_reg),
    .rst(s_axi_aresetn)
  );
  (* src = "axi_apb_bridge.v:123.2-123.81" *)
  \$paramod\flop\width=s32'00000000000000000000000000100000  timeout_counter_ff (
    .clk(s_axi_clk),
    .d(timeout_counter_nxt),
    .q(timeout_counter),
    .rst(s_axi_aresetn)
  );
  (* src = "axi_apb_bridge.v:87.2-87.78" *)
  \$paramod\flop\width=s32'00000000000000000000000000000001  write_happened_ff (
    .clk(s_axi_clk),
    .d(write_happened_nxt),
    .q(write_happened),
    .rst(s_axi_aresetn)
  );
  (* src = "axi_apb_bridge.v:118.2-118.66" *)
  \$paramod\flop\width=s32'00000000000000000000000000000010  write_resp_ff (
    .clk(s_axi_clk),
    .d(write_resp_nxt),
    .q(write_resp),
    .rst(s_axi_aresetn)
  );
  (* src = "axi_apb_bridge.v:97.2-97.88" *)
  \$paramod\flop\width=s32'00000000000000000000000000000001  write_resp_valid_ff (
    .clk(s_axi_clk),
    .d(write_resp_valid_nxt),
    .q(write_resp_valid_reg),
    .rst(s_axi_aresetn)
  );
  assign apb_transfer_req = STREQ;
  assign axi_write_data_reg = SWDATA;
  assign captured_addr = SADDR;
  assign dummy = 32'd64;
  assign m_apb_pprot = 3'h0;
  assign s_axi_bresp = write_resp;
  assign s_axi_bvalid = write_resp_valid_reg;
  assign s_axi_rdata = read_data_reg;
  assign s_axi_rresp = read_resp;
  assign s_axi_rvalid = read_valid_reg;
  assign strb = s_axi_wstrb[1:0];
  assign write_req = SWRT;
endmodule
